// ── HELT QUESTION BANK ───────────────────────────────────────
// 3 rotating sets · Reading (5 MCQ) · Listening (5 MCQ) · Writing · Speaking (2 Qs)

const QSETS = [
// ─── SET A ─────────────────────────────────────────────────
{ id:'A',
  reading:{
    passage:`The Silk Road was one of the most consequential trade networks in human history, stretching over 6,400 kilometres from East Asia to the Mediterranean. Rather than a single road, it comprised a vast web of overland and maritime routes through which merchants, monks, soldiers, and diplomats travelled for centuries. The network was instrumental in the exchange of goods such as silk, spices, precious metals, and glassware, but its cultural impact was equally profound. Religions, philosophies, artistic styles, languages, and technologies migrated along these same routes. Buddhism, Islam, and Christianity all spread partly through the Silk Road's corridors. The term itself was coined by the German geographer Ferdinand von Richthofen in 1877, though the network had been active since at least the second century BCE under the Han Dynasty of China. Caravanserais—roadside inns offering shelter, water, and food to travellers—dotted the routes and served as nodes of cultural exchange. The road declined in importance after the fifteenth century as European maritime powers developed faster sea routes to Asia, fundamentally altering global trade geography.`,
    questions:[
      { id:'R1', text:'What does the passage say about the physical nature of the Silk Road?', options:['It was a single well-paved road across Central Asia.','It was a network of both overland and maritime routes.','It was exclusively an ocean trade route.','It connected only China and Rome.'], answer:1 },
      { id:'R2', text:'Who coined the term "Silk Road", and when?', options:['A Chinese Han Dynasty emperor in the 2nd century BCE','Ferdinand von Richthofen in 1877','An Islamic scholar during the 12th century','A British geographer in the 19th century'], answer:1 },
      { id:'R3', text:'According to the passage, which of the following BEST describes the cultural impact of the Silk Road?', options:['It caused one religion to dominate the world.','It led to the spread of religions, philosophies, arts, and technologies.','Its impact was mainly economic rather than cultural.','It only benefited China and Europe.'], answer:1 },
      { id:'R4', text:'What were caravanserais, as described in the passage?', options:['Military forts protecting trade caravans','Roadside inns offering shelter and services to travellers','Local markets where goods were sold','Diplomatic embassies between trading nations'], answer:1 },
      { id:'R5', text:'Why did the Silk Road decline after the 15th century?', options:['Wars destroyed the overland routes permanently.','European powers developed faster sea routes to Asia.','China closed its borders to all foreign trade.','Plague wiped out most of the merchant populations.'], answer:1 }
    ]
  },
  listening:{
    transcript:`Welcome to Global Education Today, Episode 47. I'm your host, and today we are discussing why critical thinking is widely regarded as the most valuable skill in the 21st-century workplace. My guest is Dr. Farid Ahmadi, an educational researcher at the University of Kabul.\n\nHost: Dr. Ahmadi, what exactly is critical thinking?\nDr. Ahmadi: Critical thinking means analysing information objectively and making well-reasoned judgements. It is fundamentally different from simply memorising facts or following instructions.\nHost: Why is this skill particularly important today?\nDr. Ahmadi: The modern workplace is changing at an extraordinary pace. Artificial intelligence and automation are replacing routine tasks at scale. Employers therefore need professionals who can evaluate complex, ambiguous situations and devise creative solutions to novel problems. The World Economic Forum consistently ranks critical thinking among the top three skills sought by employers globally.\nHost: What should educational institutions do about this?\nDr. Ahmadi: Schools and universities must move decisively beyond rote learning. Project-based learning, structured debates, and Socratic questioning are all evidence-based methods. Finland's education system is frequently cited as a model — students there spend significantly less time on standardised testing and considerably more on collaborative problem-solving.\nHost: Any personal advice for learners listening today?\nDr. Ahmadi: Read widely and across different viewpoints. Practise questioning your own assumptions. And write regularly — the discipline of writing forces you to organise and interrogate your own thinking in a way nothing else does. Thank you.`,
    questions:[
      { id:'L1', text:'According to Dr. Ahmadi, how is critical thinking different from ordinary learning?', options:['It requires memorising more facts.','It involves analysing information and making reasoned judgements.','It is mainly about following instructions precisely.','It focuses on speed and efficiency at work.'], answer:1 },
      { id:'L2', text:'Why does Dr. Ahmadi say critical thinking is especially important today?', options:['Because universities now require it for admission.','Because AI and automation are replacing routine tasks.','Because international travel has increased.','Because companies are expanding globally.'], answer:1 },
      { id:'L3', text:'Which international body ranks critical thinking among the top skills sought by employers?', options:['United Nations','World Health Organization','World Economic Forum','International Labour Organization'], answer:2 },
      { id:'L4', text:'Which country\'s education system does Dr. Ahmadi praise as a model?', options:['Germany','Finland','Canada','Singapore'], answer:1 },
      { id:'L5', text:'What personal habit does Dr. Ahmadi say best sharpens analytical thinking?', options:['Watching documentaries','Writing regularly','Attending workshops','Reading only academic journals'], answer:1 }
    ]
  },
  writing:{ type:'ideas', prompt:'Some people argue that universities should be free for all students, funded entirely by governments. Others believe students should pay tuition fees since they are the primary beneficiaries of higher education. Discuss both views and give your own well-reasoned opinion. Support your argument with specific examples. (Minimum 220 words)', minWords:220 },
  speaking:[
    'Describe a teacher, mentor, or leader who has had a significant positive impact on your life. What specific qualities made them effective, and how have they influenced the person you are today?',
    'Do you believe that technology has improved or harmed human relationships overall? Use specific examples and evidence to support your position clearly.'
  ]
},

// ─── SET B ─────────────────────────────────────────────────
{ id:'B',
  reading:{
    passage:`Climate change refers to long-term shifts in global temperatures and weather patterns. While natural processes have always influenced Earth's climate, scientific consensus holds that since the mid-20th century, human activities have become the dominant driver of observed changes. The burning of fossil fuels — coal, petroleum, and natural gas — releases carbon dioxide and methane, greenhouse gases that trap solar radiation that would otherwise escape into space. This enhanced greenhouse effect is causing global average surface temperatures to rise at an unprecedented rate. The consequences are already measurable: more frequent and intense extreme weather events, including hurricanes, prolonged droughts, and catastrophic flooding; sea level rise attributable to the melting of polar ice sheets and glaciers; and widespread disruption to terrestrial and marine ecosystems. The Intergovernmental Panel on Climate Change warns that limiting global warming to 1.5°C above pre-industrial levels — the threshold scientists consider critical — requires rapid and far-reaching transitions in energy production, land use, transportation, and industry by 2050. Nations have signed international agreements, most notably the Paris Agreement of 2015, committing to reduce greenhouse gas emissions and strengthen climate resilience.`,
    questions:[
      { id:'R1', text:'According to the passage, what has been the dominant driver of climate change since the mid-20th century?', options:['Natural volcanic eruptions','Changes in Earth\'s orbital cycle','Human activities, especially burning fossil fuels','Deforestation by large animals'], answer:2 },
      { id:'R2', text:'How do greenhouse gases contribute to global warming, according to the passage?', options:['They block rainfall from reaching the surface.','They trap solar radiation that would otherwise escape into space.','They directly melt polar ice by generating heat.','They absorb sunlight before it reaches the Earth.'], answer:1 },
      { id:'R3', text:'Which of the following consequences of climate change is NOT mentioned in the passage?', options:['More frequent extreme weather events','Sea level rise','Extinction of all ocean fish','Disruption to ecosystems'], answer:2 },
      { id:'R4', text:'What temperature limit does the IPCC identify as a critical warming threshold?', options:['2.5°C above current levels','3°C above 1990 averages','1.5°C above pre-industrial levels','0.5°C above 1950 baseline'], answer:2 },
      { id:'R5', text:'The word "unprecedented" in the passage most closely means:', options:['Expected and well-documented','Moderate and manageable','Never having occurred before at this scale','Slowly progressing'], answer:2 }
    ]
  },
  listening:{
    transcript:`Welcome to Future Forward, Episode 12. Today we are exploring the rise of remote work and its long-term implications for workers, organisations, and society. My guest is Ms. Nilufar Rashidi, a human resources and organisational development consultant.\n\nHost: Ms. Rashidi, how significant has the shift to remote work really been?\nMs. Rashidi: It has been transformational. Before 2020, remote work was an occasional perk for a minority of workers. Since then, it has become a standard expectation for professionals across a wide range of industries. What was once the exception is now the norm for many knowledge workers worldwide.\nHost: What are the most significant benefits?\nMs. Rashidi: Flexibility is undoubtedly the most valued benefit. Employees can structure their time around both professional and personal needs, which typically leads to higher job satisfaction. Numerous studies demonstrate that productivity often increases for tasks requiring sustained, deep concentration when people work from home.\nHost: Are there genuine disadvantages?\nMs. Rashidi: Absolutely. Social isolation is a serious concern. Spontaneous, informal collaboration — the kind that leads to breakthrough ideas — is much harder to replicate digitally. Organisations must invest deliberately in digital communication infrastructure and intentional team-building practices.\nHost: What about career development?\nMs. Rashidi: This is a critical point often overlooked. Junior employees are especially at risk of missing informal mentorship — the kind of guidance that happens naturally in physical office environments. Organisations need structured mentoring programmes to compensate. I believe the future will be a well-designed hybrid model: some days remote, some in-office, carefully balancing flexibility with the human connection that drives innovation. Thank you.`,
    questions:[
      { id:'L1', text:'According to Ms. Rashidi, what has remote work become for many professionals since 2020?', options:['A temporary emergency measure','A standard expectation across many industries','A benefit reserved for senior employees only','A practice limited to the technology sector'], answer:1 },
      { id:'L2', text:'What does Ms. Rashidi identify as the most valued benefit of remote work?', options:['Higher salaries','Flexibility','Faster career advancement','Better office equipment'], answer:1 },
      { id:'L3', text:'Which type of work does Ms. Rashidi say benefits most from the home environment?', options:['Tasks requiring constant client interaction','Tasks requiring physical presence','Tasks requiring sustained deep concentration','Tasks requiring large team coordination'], answer:2 },
      { id:'L4', text:'What specific concern does Ms. Rashidi raise about junior employees working remotely?', options:['They earn lower wages than office colleagues.','They miss out on informal mentorship that happens naturally in offices.','They have less access to digital tools.','They struggle to manage different time zones.'], answer:1 },
      { id:'L5', text:'What future work model does Ms. Rashidi predict and advocate for?', options:['Fully remote work for all employees globally','A return to five-day in-office schedules','A well-designed hybrid model balancing remote and in-office days','Four-day working weeks with mandatory office attendance'], answer:2 }
    ]
  },
  writing:{ type:'ideas', prompt:'Many researchers and educators argue that the widespread use of social media platforms has had a significantly negative impact on young people\'s mental health, social skills, and academic performance. To what extent do you agree or disagree with this assessment? Provide specific evidence, examples, and counterarguments to develop your position thoroughly. (Minimum 220 words)', minWords:220 },
  speaking:[
    'What do you consider the most important qualities of an effective leader? Use specific examples of leaders you admire — whether from history, public life, or your own experience — to illustrate your points.',
    'Should governments prioritise investing in space exploration, or should all available resources be directed toward solving urgent problems on Earth such as poverty, disease, and climate change? Argue your position clearly.'
  ]
},

// ─── SET C ─────────────────────────────────────────────────
{ id:'C',
  reading:{
    passage:`Artificial intelligence — commonly abbreviated as AI — refers to the simulation of human cognitive processes by computer systems. These processes include learning from experience, reasoning through problems, and correcting errors autonomously. AI applications now span an extraordinary range of fields: from relatively simple rule-based systems that automate repetitive administrative tasks, to sophisticated neural networks capable of recognising faces, translating between dozens of languages in real time, generating photorealistic imagery, and composing original music. Machine learning, a central subset of AI, enables systems to improve their performance through exposure to data without being explicitly reprogrammed for each new scenario. Deep learning, a further refinement, employs layered artificial neural networks to detect subtle patterns in vast datasets, achieving human-level or superhuman accuracy in tasks such as medical image analysis and protein structure prediction. Despite its remarkable promise — in medicine, agriculture, education, climate science, and beyond — AI raises profound ethical challenges: algorithmic bias that perpetuates social inequalities; erosion of privacy through mass data collection; large-scale displacement of workers from routine and even complex jobs; and the concentration of transformative power in the hands of a very small number of technology corporations. Responsible AI development requires transparent regulatory frameworks, diverse and inclusive research teams, independent auditing mechanisms, and sustained public deliberation about the values that should guide automated decision-making.`,
    questions:[
      { id:'R1', text:'According to the passage, which of the following is a subset of artificial intelligence?', options:['Robotics engineering','Machine learning','Computer hardware design','Data storage infrastructure'], answer:1 },
      { id:'R2', text:'What does deep learning use to detect patterns in large datasets?', options:['Traditional rule-based programming','Physical sensors and cameras','Layered artificial neural networks','Statistical regression models'], answer:2 },
      { id:'R3', text:'Which application of AI achieving human-level accuracy is mentioned in the passage?', options:['Autonomous vehicle navigation','Medical image analysis','Social media content moderation','Financial market prediction'], answer:1 },
      { id:'R4', text:'Which ethical concern relates to AI systems producing unfair outcomes due to biased training data?', options:['Deep learning inaccuracy','Algorithmic bias','Neural network complexity','Machine translation errors'], answer:1 },
      { id:'R5', text:'The passage argues that responsible AI development requires all of the following EXCEPT:', options:['Transparent regulatory frameworks','Diverse and inclusive research teams','Restricting AI exclusively to government use','Independent auditing mechanisms'], answer:2 }
    ]
  },
  listening:{
    transcript:`Welcome to Health Horizons, Episode 31. Today's conversation focuses on the global mental health crisis — its scale, its causes, and the most promising solutions emerging around the world. I am joined by Dr. Samira Yusuf, a psychiatrist and public health advocate.\n\nHost: Dr. Yusuf, just how serious is the global mental health situation?\nDr. Yusuf: It is genuinely alarming. Mental health conditions affect approximately one in four people worldwide at some point in their lives. Yet globally, less than two percent of national health budgets are allocated to mental health services. The treatment gap — the difference between those who need care and those who receive it — exceeds seventy percent in low-income countries.\nHost: What are the main barriers to accessing care?\nDr. Yusuf: Stigma is perhaps the greatest single barrier. In many cultures, admitting to a mental health condition is associated with weakness, moral failure, or family shame. This deeply discourages help-seeking behaviour. Beyond stigma, trained mental health professionals are concentrated in wealthy urban centres, leaving rural populations severely underserved.\nHost: What solutions are showing the most promise?\nDr. Yusuf: Task-shifting is a genuinely effective and scalable approach — training community health workers and lay volunteers to deliver basic psychological first aid and evidence-based talk therapies. Digital platforms and smartphone applications have demonstrated real promise in reaching isolated or stigmatised individuals. And public communication campaigns that use authentic storytelling to normalise mental health conversations have measurably reduced stigma in several countries.\nHost: What can individuals listening right now do?\nDr. Yusuf: Talk about mental health openly with those around you. Check in regularly on friends and family members. And if you yourself are struggling, please reach out to a professional — doing so is a genuine act of courage, not weakness. Thank you.`,
    questions:[
      { id:'L1', text:'What percentage of national health budgets are typically allocated to mental health services globally?', options:['Less than 2%','Approximately 10%','Around 25%','More than 15%'], answer:0 },
      { id:'L2', text:'According to Dr. Yusuf, what is perhaps the greatest single barrier to mental health care?', options:['Lack of hospitals and clinics','Stigma associated with mental illness','High costs of medication','Insufficient government funding'], answer:1 },
      { id:'L3', text:'What is "task-shifting" as described by Dr. Yusuf?', options:['Moving mental health funding to physical health budgets','Training community workers to deliver basic psychological support','Relocating psychiatrists from cities to rural areas','Shifting from medication to purely talking therapies'], answer:1 },
      { id:'L4', text:'What technology does Dr. Yusuf highlight as promising for reaching isolated individuals?', options:['Television documentaries','Community radio programmes','Smartphone applications and digital platforms','Satellite-based telemedicine clinics'], answer:2 },
      { id:'L5', text:'Dr. Yusuf says seeking professional help is a sign of:', options:['Weakness and vulnerability','Failure and giving up','Courage and strength','Desperation and hopelessness'], answer:2 }
    ]
  },
  writing:{ type:'ideas', prompt:'It is often argued that learning a second or third language is one of the most valuable investments a young person can make — for their career, their cultural understanding, and their cognitive development. However, others argue that time spent on additional languages would be better invested in technical or vocational skills. Discuss both perspectives and give your own carefully reasoned opinion with specific examples. (Minimum 220 words)', minWords:220 },
  speaking:[
    'Describe a significant challenge or failure you have experienced in your life. How did you respond to it, what did you learn from the experience, and how has it shaped who you are today?',
    'In your view, what are the most pressing responsibilities that wealthy nations have toward developing countries? Should foreign aid be unconditional, or should it come with specific requirements? Argue your position with reasons and examples.'
  ]
}
];

const SCORE_CFG = { reading:{total:25,perQ:5,n:5}, listening:{total:25,perQ:5,n:5}, writing:{total:25}, speaking:{total:25} };

function getQSet() {
  const i = parseInt(S.get('qSetIdx',0));
  return QSETS[i % QSETS.length];
}

function getProfLevel(t) {
  if (t>=85) return {level:'Advanced',band:'C1–C2',color:'#1E7A4A'};
  if (t>=65) return {level:'Intermediate',band:'B1–B2',color:'#B5620A'};
  if (t>=40) return {level:'Basic',band:'A2–B1',color:'#8A6A00'};
  return            {level:'Elementary',band:'A1',color:'#9B2316'};
}
